FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# 開発用にホットリロードを有効にする
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]